/**
 * DATA SUBJECT RELATION GRAPH & DEPENDENCY TREE — VELVET
 *
 * Phase: LGPD-01
 * Models all relationship graphs, foreign keys, cascade rules, and orphan risks.
 */

export interface RelationNode {
  tableName: string
  rootIdentity: 'auth.users' | 'account_users' | 'professional_profiles' | 'visitor_session' | 'system'
  foreignKeyColumn: string
  targetTable: string
  targetColumn: string
  onDeleteAction: 'CASCADE' | 'RESTRICT' | 'SET NULL' | 'NO ACTION' | 'NONE'
  orphanRisk: 'HIGH' | 'MEDIUM' | 'LOW' | 'NONE'
  manualCleanupRequired: boolean
  description: string
}

export const DATA_SUBJECT_RELATION_GRAPH: readonly RelationNode[] = [
  // ---------------------------------------------------------------------------
  // LEVEL 0 -> LEVEL 1: Auth User to Account User
  // ---------------------------------------------------------------------------
  {
    tableName: 'account_users',
    rootIdentity: 'auth.users',
    foreignKeyColumn: 'auth_user_id',
    targetTable: 'auth.users',
    targetColumn: 'id',
    onDeleteAction: 'CASCADE',
    orphanRisk: 'LOW',
    manualCleanupRequired: false,
    description: 'Direct link between Supabase Auth identity and Velvet account record.',
  },

  // ---------------------------------------------------------------------------
  // LEVEL 1 -> LEVEL 2: Direct Account Children
  // ---------------------------------------------------------------------------
  {
    tableName: 'professional_profiles',
    rootIdentity: 'account_users',
    foreignKeyColumn: 'account_user_id',
    targetTable: 'account_users',
    targetColumn: 'id',
    onDeleteAction: 'CASCADE',
    orphanRisk: 'LOW',
    manualCleanupRequired: false,
    description: 'Professional advertiser profile. Cascades if account_users row is deleted.',
  },
  {
    tableName: 'identity_verifications',
    rootIdentity: 'account_users',
    foreignKeyColumn: 'account_user_id',
    targetTable: 'account_users',
    targetColumn: 'id',
    onDeleteAction: 'CASCADE',
    orphanRisk: 'LOW',
    manualCleanupRequired: false,
    description: 'KYC status record. Cascades with account.',
  },
  {
    tableName: 'client_memberships',
    rootIdentity: 'account_users',
    foreignKeyColumn: 'account_id',
    targetTable: 'account_users',
    targetColumn: 'id',
    onDeleteAction: 'CASCADE',
    orphanRisk: 'LOW',
    manualCleanupRequired: false,
    description: 'Client membership tier. Cascades with account.',
  },
  {
    tableName: 'subscriptions',
    rootIdentity: 'account_users',
    foreignKeyColumn: 'account_id',
    targetTable: 'account_users',
    targetColumn: 'id',
    onDeleteAction: 'CASCADE',
    orphanRisk: 'LOW',
    manualCleanupRequired: false,
    description: 'Subscription contracts for advertiser.',
  },
  {
    tableName: 'billing_overrides',
    rootIdentity: 'account_users',
    foreignKeyColumn: 'account_user_id',
    targetTable: 'account_users',
    targetColumn: 'id',
    onDeleteAction: 'CASCADE',
    orphanRisk: 'LOW',
    manualCleanupRequired: false,
    description: 'Commercial entitlement overrides.',
  },
  {
    tableName: 'entitlement_overrides',
    rootIdentity: 'account_users',
    foreignKeyColumn: 'account_user_id',
    targetTable: 'account_users',
    targetColumn: 'id',
    onDeleteAction: 'CASCADE',
    orphanRisk: 'LOW',
    manualCleanupRequired: false,
    description: 'Granular entitlement overrides.',
  },
  {
    tableName: 'billing_admin_audit_logs',
    rootIdentity: 'account_users',
    foreignKeyColumn: 'target_account_user_id',
    targetTable: 'account_users',
    targetColumn: 'id',
    onDeleteAction: 'SET NULL',
    orphanRisk: 'NONE',
    manualCleanupRequired: false,
    description: 'Audit log of billing overrides. SET NULL preserves audit trail.',
  },
  {
    tableName: 'data_subject_requests',
    rootIdentity: 'account_users',
    foreignKeyColumn: 'requester_account_user_id',
    targetTable: 'account_users',
    targetColumn: 'id',
    onDeleteAction: 'RESTRICT',
    orphanRisk: 'NONE',
    manualCleanupRequired: true,
    description: 'DSR ledger. RESTRICT prevents deleting account_user while request is unresolved.',
  },

  // ---------------------------------------------------------------------------
  // LEVEL 2 -> LEVEL 3: Professional Profile Children
  // ---------------------------------------------------------------------------
  {
    tableName: 'professional_profile_locations',
    rootIdentity: 'professional_profiles',
    foreignKeyColumn: 'profile_id',
    targetTable: 'professional_profiles',
    targetColumn: 'id',
    onDeleteAction: 'CASCADE',
    orphanRisk: 'LOW',
    manualCleanupRequired: false,
    description: 'Service area associations. Cascades with profile.',
  },
  {
    tableName: 'professional_profile_offerings',
    rootIdentity: 'professional_profiles',
    foreignKeyColumn: 'profile_id',
    targetTable: 'professional_profiles',
    targetColumn: 'id',
    onDeleteAction: 'CASCADE',
    orphanRisk: 'LOW',
    manualCleanupRequired: false,
    description: 'Services and offerings advertised. Cascades with profile.',
  },
  {
    tableName: 'profile_media',
    rootIdentity: 'professional_profiles',
    foreignKeyColumn: 'profile_id',
    targetTable: 'professional_profiles',
    targetColumn: 'id',
    onDeleteAction: 'CASCADE',
    orphanRisk: 'HIGH',
    manualCleanupRequired: true,
    description: 'Photo records cascade in DB, BUT corresponding files in profile-media Storage bucket require manual coordinated deletion!',
  },
  {
    tableName: 'profile_videos',
    rootIdentity: 'professional_profiles',
    foreignKeyColumn: 'profile_id',
    targetTable: 'professional_profiles',
    targetColumn: 'id',
    onDeleteAction: 'CASCADE',
    orphanRisk: 'HIGH',
    manualCleanupRequired: true,
    description: 'Video records cascade in DB, BUT video and poster files in profile-videos Storage bucket require manual coordinated deletion!',
  },
  {
    tableName: 'profile_boosts',
    rootIdentity: 'professional_profiles',
    foreignKeyColumn: 'profile_id',
    targetTable: 'professional_profiles',
    targetColumn: 'id',
    onDeleteAction: 'CASCADE',
    orphanRisk: 'LOW',
    manualCleanupRequired: false,
    description: 'Promotional boost campaigns for the profile.',
  },
  {
    tableName: 'profile_daily_metrics',
    rootIdentity: 'professional_profiles',
    foreignKeyColumn: 'profile_id',
    targetTable: 'professional_profiles',
    targetColumn: 'id',
    onDeleteAction: 'CASCADE',
    orphanRisk: 'LOW',
    manualCleanupRequired: false,
    description: 'Daily metrics aggregated counters. Cascades with profile.',
  },
  {
    tableName: 'professional_availability_settings',
    rootIdentity: 'professional_profiles',
    foreignKeyColumn: 'profile_id',
    targetTable: 'professional_profiles',
    targetColumn: 'id',
    onDeleteAction: 'CASCADE',
    orphanRisk: 'LOW',
    manualCleanupRequired: false,
    description: 'Agenda settings. Cascades with profile.',
  },
  {
    tableName: 'professional_weekly_availability',
    rootIdentity: 'professional_profiles',
    foreignKeyColumn: 'profile_id',
    targetTable: 'professional_profiles',
    targetColumn: 'id',
    onDeleteAction: 'CASCADE',
    orphanRisk: 'LOW',
    manualCleanupRequired: false,
    description: 'Recurring schedule slots. Cascades with profile.',
  },
  {
    tableName: 'professional_availability_exceptions',
    rootIdentity: 'professional_profiles',
    foreignKeyColumn: 'profile_id',
    targetTable: 'professional_profiles',
    targetColumn: 'id',
    onDeleteAction: 'CASCADE',
    orphanRisk: 'LOW',
    manualCleanupRequired: false,
    description: 'Agenda exception dates. Cascades with profile.',
  },
  {
    tableName: 'professional_concierge_settings',
    rootIdentity: 'professional_profiles',
    foreignKeyColumn: 'profile_id',
    targetTable: 'professional_profiles',
    targetColumn: 'id',
    onDeleteAction: 'CASCADE',
    orphanRisk: 'LOW',
    manualCleanupRequired: false,
    description: 'AI Concierge configuration. Cascades with profile.',
  },
  {
    tableName: 'professional_concierge_faqs',
    rootIdentity: 'professional_profiles',
    foreignKeyColumn: 'profile_id',
    targetTable: 'professional_profiles',
    targetColumn: 'id',
    onDeleteAction: 'CASCADE',
    orphanRisk: 'LOW',
    manualCleanupRequired: false,
    description: 'Custom FAQs for concierge. Cascades with profile.',
  },
  {
    tableName: 'concierge_conversations',
    rootIdentity: 'professional_profiles',
    foreignKeyColumn: 'profile_id',
    targetTable: 'professional_profiles',
    targetColumn: 'id',
    onDeleteAction: 'CASCADE',
    orphanRisk: 'LOW',
    manualCleanupRequired: false,
    description: 'Visitor chat sessions. Cascades with profile.',
  },
  {
    tableName: 'concierge_messages',
    rootIdentity: 'professional_profiles',
    foreignKeyColumn: 'conversation_id',
    targetTable: 'concierge_conversations',
    targetColumn: 'id',
    onDeleteAction: 'CASCADE',
    orphanRisk: 'LOW',
    manualCleanupRequired: false,
    description: 'Chat messages. Cascades with conversation.',
  },
  {
    tableName: 'professional_profile_status_events',
    rootIdentity: 'professional_profiles',
    foreignKeyColumn: 'profile_id',
    targetTable: 'professional_profiles',
    targetColumn: 'id',
    onDeleteAction: 'CASCADE',
    orphanRisk: 'LOW',
    manualCleanupRequired: false,
    description: 'Profile status transition audit ledger. Cascades with profile.',
  },

  // ---------------------------------------------------------------------------
  // CLIENT ACTIVITY & COMMUNITY CONTENT
  // ---------------------------------------------------------------------------
  {
    tableName: 'professional_reviews',
    rootIdentity: 'account_users',
    foreignKeyColumn: 'reviewer_account_user_id',
    targetTable: 'account_users',
    targetColumn: 'id',
    onDeleteAction: 'CASCADE',
    orphanRisk: 'MEDIUM',
    manualCleanupRequired: true,
    description: 'Reviews written by client. In LGPD deletion, reviews must be evaluated for anonymization instead of abrupt CASCADE to preserve professional profile reputation integrity.',
  },
  {
    tableName: 'professional_review_responses',
    rootIdentity: 'account_users',
    foreignKeyColumn: 'professional_account_user_id',
    targetTable: 'account_users',
    targetColumn: 'id',
    onDeleteAction: 'CASCADE',
    orphanRisk: 'LOW',
    manualCleanupRequired: false,
    description: 'Professional responses to reviews. Cascades with review.',
  },
  {
    tableName: 'review_reports',
    rootIdentity: 'account_users',
    foreignKeyColumn: 'reporter_account_user_id',
    targetTable: 'account_users',
    targetColumn: 'id',
    onDeleteAction: 'CASCADE',
    orphanRisk: 'LOW',
    manualCleanupRequired: false,
    description: 'Abuse reports on reviews. Cascades with review.',
  },

  // ---------------------------------------------------------------------------
  // MODERATION LEDGERS & RESTRICT CONSTRAINTS
  // ---------------------------------------------------------------------------
  {
    tableName: 'profile_moderation_reviews',
    rootIdentity: 'professional_profiles',
    foreignKeyColumn: 'profile_id',
    targetTable: 'professional_profiles',
    targetColumn: 'id',
    onDeleteAction: 'CASCADE',
    orphanRisk: 'LOW',
    manualCleanupRequired: false,
    description: 'Profile content moderation audit logs.',
  },
  {
    tableName: 'media_moderation_reviews',
    rootIdentity: 'professional_profiles',
    foreignKeyColumn: 'media_id',
    targetTable: 'profile_media',
    targetColumn: 'id',
    onDeleteAction: 'CASCADE',
    orphanRisk: 'LOW',
    manualCleanupRequired: false,
    description: 'Media moderation audit logs.',
  },
  {
    tableName: 'content_reports',
    rootIdentity: 'professional_profiles',
    foreignKeyColumn: 'profile_id',
    targetTable: 'professional_profiles',
    targetColumn: 'id',
    onDeleteAction: 'CASCADE',
    orphanRisk: 'LOW',
    manualCleanupRequired: false,
    description: 'Abuse reports tied to profile.',
  },
] as const
