import type { DataInventoryItem } from './types'

/**
 * CANONICAL MACHINE-READABLE PRIVACY DATA INVENTORY — VELVET
 *
 * Phase: LGPD-01.1 Closure
 * Audit baseline: Dev database schema, Supabase Auth, Storage buckets, client cookies.
 *
 * Invariants:
 * - Zero secrets or credential values.
 * - Explicit classification and sensitivity level per item.
 * - Clear distinction: SENSITIVE_DATA_CONFIRMED, POTENTIALLY_SENSITIVE_FREE_TEXT,
 *   HIGH_RISK_BUT_NOT_CLASSIFIED_AS_SENSITIVE, NOT_SENSITIVE.
 * - No fictitious legal bases encoded.
 * - All retention periods marked UNDEFINED (LEGAL_APPROVAL_REQUIRED).
 */
export const CANONICAL_DATA_INVENTORY: readonly DataInventoryItem[] = [
  // ---------------------------------------------------------------------------
  // AUTHENTICATION & IDENTITY ROOT
  // ---------------------------------------------------------------------------
  {
    id: 'AUTH_USERS',
    system: 'SUPABASE_AUTH',
    storage_object: 'auth.users',
    subject_role: 'ADVERTISER',
    data_category: 'CREDENTIALS_AND_METADATA',
    classification: 'AUTHENTICATION',
    sensitivity_level: 'NOT_SENSITIVE',
    source: 'USER_INPUT',
    purpose: 'Core authentication, identity credential management, session issuance.',
    legal_basis_status: 'SOURCE_CONFIRMED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'DELETE',
    external_processors: ['Supabase Inc.'],
    notes: 'Stores email, encrypted password hash, phone, email confirmation timestamp, raw_user_meta_data. Credentials are security-critical but not LGPD Art. 5, II sensitive data.',
  },
  {
    id: 'ACCOUNT_USERS',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.account_users',
    subject_role: 'ADVERTISER',
    data_category: 'ACCOUNT_PROFILE',
    classification: 'PRIVATE_PERSONAL',
    sensitivity_level: 'NOT_SENSITIVE',
    source: 'SYSTEM_DERIVED',
    purpose: 'Velvet domain account root, role management, onboarding progress, legal version acceptance.',
    legal_basis_status: 'SOURCE_CONFIRMED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'DELETE',
    external_processors: ['Supabase Inc.'],
    notes: 'Links auth.users via auth_user_id. Tracks terms_accepted_at and privacy_accepted_at.',
  },
  {
    id: 'CLIENT_SIGNUP_INTENTS',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.client_signup_intents',
    subject_role: 'CLIENT',
    data_category: 'AUTHENTICATION_FLOW',
    classification: 'OPERATIONAL_SECURITY',
    sensitivity_level: 'NOT_SENSITIVE',
    source: 'SYSTEM_DERIVED',
    purpose: 'Short-lived single-use signup intent token for verifying client role creation without trust of client payload.',
    legal_basis_status: 'SOURCE_CONFIRMED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'DELETE',
    external_processors: ['Supabase Inc.'],
    notes: 'Stores token_hash (SHA-256), consumed_at, auth_user_id. Short 10-minute TTL.',
  },

  // ---------------------------------------------------------------------------
  // KYC & IDENTITY VERIFICATION
  // ---------------------------------------------------------------------------
  {
    id: 'IDENTITY_VERIFICATIONS',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.identity_verifications',
    subject_role: 'ADVERTISER',
    data_category: 'IDENTITY_VERIFICATION',
    classification: 'KYC_REFERENCE',
    sensitivity_level: 'HIGH_RISK_BUT_NOT_CLASSIFIED_AS_SENSITIVE',
    source: 'EXTERNAL_PROVIDER',
    purpose: 'Authoritative confirmation of majority (18+) and identity validity prior to advertising.',
    legal_basis_status: 'LEGAL_APPROVAL_REQUIRED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'RETAIN_IF_LEGALLY_REQUIRED',
    external_processors: ['Didit', 'Supabase Inc.'],
    notes: 'Velvet stores provider session ID, status, flags (identity_verified, age_verified, cpf_verified). Does NOT store raw documents, selfies, biometrics or CPF numbers locally. Biometric comparison is executed externally by Didit.',
  },
  {
    id: 'VERIFICATION_WEBHOOK_EVENTS',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.verification_webhook_events',
    subject_role: 'SYSTEM',
    data_category: 'KYC_WEBHOOK_AUDIT',
    classification: 'AUDIT_RECORD',
    sensitivity_level: 'NOT_SENSITIVE',
    source: 'EXTERNAL_PROVIDER',
    purpose: 'Idempotency and audit log for Didit verification webhook deliveries.',
    legal_basis_status: 'SOURCE_CONFIRMED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'ANONYMIZE',
    external_processors: ['Didit', 'Supabase Inc.'],
    notes: 'Stores provider event IDs and delivery status. Does not store biometric bytes or identity scans.',
  },

  // ---------------------------------------------------------------------------
  // PROFESSIONAL PROFILES & PUBLIC DETAILS
  // ---------------------------------------------------------------------------
  {
    id: 'PROFESSIONAL_PROFILES',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.professional_profiles',
    subject_role: 'ADVERTISER',
    data_category: 'PUBLIC_PROFILE_CONTENT',
    classification: 'PUBLIC_PERSONAL',
    sensitivity_level: 'POTENTIALLY_SENSITIVE_FREE_TEXT',
    source: 'USER_INPUT',
    purpose: 'Public advertisement profile, contact channels, physical attributes, bio.',
    legal_basis_status: 'SOURCE_CONFIRMED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'DELETE',
    external_processors: ['Supabase Inc.'],
    notes: 'Bio and headline are free text that may describe intimate preferences or boundaries. Physical measurements are descriptive attributes (high-risk in adult context but not Art. 5, II biometric data).',
  },
  {
    id: 'PROFESSIONAL_PROFILE_LOCATIONS',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.professional_profile_locations',
    subject_role: 'ADVERTISER',
    data_category: 'SERVICE_AREAS',
    classification: 'PUBLIC_PERSONAL',
    sensitivity_level: 'NOT_SENSITIVE',
    source: 'USER_INPUT',
    purpose: 'Associates professional profiles with marketplace neighborhoods/cities for local search discovery.',
    legal_basis_status: 'SOURCE_CONFIRMED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'DELETE',
    external_processors: ['Supabase Inc.'],
    notes: 'Links profile_id with marketplace_locations(id). Geographic area only.',
  },
  {
    id: 'PROFESSIONAL_PROFILE_OFFERINGS',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.professional_profile_offerings',
    subject_role: 'ADVERTISER',
    data_category: 'COMMERCIAL_SERVICES',
    classification: 'PUBLIC_PERSONAL',
    sensitivity_level: 'SENSITIVE_DATA_CONFIRMED',
    source: 'USER_INPUT',
    purpose: 'Specific adult services and audience preferences offered by the professional.',
    legal_basis_status: 'LEGAL_APPROVAL_REQUIRED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'DELETE',
    external_processors: ['Supabase Inc.'],
    notes: 'SENSITIVE DATA CONFIRMED: Options include adult sexual services (oral, anal, bdsm, fetishes) and target sexual audience (men, women, couples), which directly relate to sexual life under LGPD Art. 5, II.',
  },

  // ---------------------------------------------------------------------------
  // MEDIA STORAGE & MODERATION
  // ---------------------------------------------------------------------------
  {
    id: 'PROFILE_MEDIA_METADATA',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.profile_media',
    subject_role: 'ADVERTISER',
    data_category: 'MEDIA_ASSETS_METADATA',
    classification: 'USER_GENERATED_CONTENT',
    sensitivity_level: 'HIGH_RISK_BUT_NOT_CLASSIFIED_AS_SENSITIVE',
    source: 'USER_INPUT',
    purpose: 'Photo metadata, dimensions, ordering, moderation status, storage path reference.',
    legal_basis_status: 'SOURCE_CONFIRMED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'DELETE',
    external_processors: ['Supabase Inc.'],
    notes: 'Metadata of adult imagery. Relates to adult profile presentation.',
  },
  {
    id: 'PROFILE_MEDIA_STORAGE',
    system: 'SUPABASE_STORAGE',
    storage_object: 'profile-media (bucket)',
    subject_role: 'ADVERTISER',
    data_category: 'MEDIA_IMAGE_FILES',
    classification: 'SENSITIVE_OR_HIGH_RISK',
    sensitivity_level: 'HIGH_RISK_BUT_NOT_CLASSIFIED_AS_SENSITIVE',
    source: 'USER_INPUT',
    purpose: 'Storage of uploaded professional photos.',
    legal_basis_status: 'LEGAL_APPROVAL_REQUIRED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'DELETE',
    external_processors: ['Supabase Inc.'],
    notes: 'HIGH RISK: Contains adult/erotic imagery of individuals. Stored in private bucket with short-lived signed URLs (1 hour). Legal review required on whether adult imagery qualifies strictly as sexual life data under Art. 5, II.',
  },
  {
    id: 'PROFILE_VIDEOS_METADATA',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.profile_videos',
    subject_role: 'ADVERTISER',
    data_category: 'MEDIA_ASSETS_METADATA',
    classification: 'USER_GENERATED_CONTENT',
    sensitivity_level: 'HIGH_RISK_BUT_NOT_CLASSIFIED_AS_SENSITIVE',
    source: 'USER_INPUT',
    purpose: 'Short video metadata, duration, poster reference, moderation status.',
    legal_basis_status: 'SOURCE_CONFIRMED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'DELETE',
    external_processors: ['Supabase Inc.'],
    notes: 'Metadata of video clips. Adult marketplace context.',
  },
  {
    id: 'PROFILE_VIDEOS_STORAGE',
    system: 'SUPABASE_STORAGE',
    storage_object: 'profile-videos (bucket)',
    subject_role: 'ADVERTISER',
    data_category: 'MEDIA_VIDEO_FILES',
    classification: 'SENSITIVE_OR_HIGH_RISK',
    sensitivity_level: 'HIGH_RISK_BUT_NOT_CLASSIFIED_AS_SENSITIVE',
    source: 'USER_INPUT',
    purpose: 'Storage of uploaded video clips and poster images.',
    legal_basis_status: 'LEGAL_APPROVAL_REQUIRED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'DELETE',
    external_processors: ['Supabase Inc.'],
    notes: 'HIGH RISK: Moving audiovisual representations of adult professionals. Private bucket, 900s signed URLs. Legal review required.',
  },
  {
    id: 'MEDIA_MODERATION_REVIEWS',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.media_moderation_reviews',
    subject_role: 'ADMIN',
    data_category: 'MODERATION_AUDIT',
    classification: 'AUDIT_RECORD',
    sensitivity_level: 'POTENTIALLY_SENSITIVE_FREE_TEXT',
    source: 'ADMINISTRATIVE_ACTION',
    purpose: 'Audit log of human moderation decisions and reason codes for photo assets.',
    legal_basis_status: 'LEGAL_APPROVAL_REQUIRED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'RETAIN_IF_LEGALLY_REQUIRED',
    external_processors: ['Supabase Inc.'],
    notes: 'Notes field may discuss intimate content reasons for rejection.',
  },
  {
    id: 'PROFILE_MODERATION_REVIEWS',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.profile_moderation_reviews',
    subject_role: 'ADMIN',
    data_category: 'MODERATION_AUDIT',
    classification: 'AUDIT_RECORD',
    sensitivity_level: 'POTENTIALLY_SENSITIVE_FREE_TEXT',
    source: 'ADMINISTRATIVE_ACTION',
    purpose: 'Audit log of human moderation decisions for text, headline, and bio changes.',
    legal_basis_status: 'LEGAL_APPROVAL_REQUIRED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'RETAIN_IF_LEGALLY_REQUIRED',
    external_processors: ['Supabase Inc.'],
    notes: 'Stores content_snapshot of user-authored bio text which may touch intimate preferences.',
  },
  {
    id: 'PROFILE_VIDEO_MODERATION_EVENTS',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.profile_video_moderation_events',
    subject_role: 'ADMIN',
    data_category: 'MODERATION_AUDIT',
    classification: 'AUDIT_RECORD',
    sensitivity_level: 'POTENTIALLY_SENSITIVE_FREE_TEXT',
    source: 'ADMINISTRATIVE_ACTION',
    purpose: 'Audit log of video moderation decisions.',
    legal_basis_status: 'LEGAL_APPROVAL_REQUIRED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'RETAIN_IF_LEGALLY_REQUIRED',
    external_processors: ['Supabase Inc.'],
    notes: 'Contains reviewer notes on video rejections.',
  },
  {
    id: 'PROFESSIONAL_PROFILE_STATUS_EVENTS',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.professional_profile_status_events',
    subject_role: 'ADMIN',
    data_category: 'LIFECYCLE_AUDIT',
    classification: 'AUDIT_RECORD',
    sensitivity_level: 'NOT_SENSITIVE',
    source: 'ADMINISTRATIVE_ACTION',
    purpose: 'Immutable audit log of profile suspension and reactivation actions.',
    legal_basis_status: 'LEGAL_APPROVAL_REQUIRED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'RETAIN_IF_LEGALLY_REQUIRED',
    external_processors: ['Supabase Inc.'],
    notes: 'Operational lifecycle events.',
  },

  // ---------------------------------------------------------------------------
  // REPORTS & ABUSE PREVENTION
  // ---------------------------------------------------------------------------
  {
    id: 'CONTENT_REPORTS',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.content_reports',
    subject_role: 'VISITOR',
    data_category: 'ABUSE_REPORTS',
    classification: 'OPERATIONAL_SECURITY',
    sensitivity_level: 'POTENTIALLY_SENSITIVE_FREE_TEXT',
    source: 'USER_INPUT',
    purpose: 'Community abuse reporting against profiles or media items.',
    legal_basis_status: 'LEGAL_APPROVAL_REQUIRED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'RETAIN_IF_LEGALLY_REQUIRED',
    external_processors: ['Supabase Inc.'],
    notes: 'Description field contains free text describing alleged violations or conduct. Reporter is pseudonymized via HMAC hash (reporter_hash).',
  },
  {
    id: 'REVIEW_REPORTS',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.review_reports',
    subject_role: 'CLIENT',
    data_category: 'ABUSE_REPORTS',
    classification: 'OPERATIONAL_SECURITY',
    sensitivity_level: 'POTENTIALLY_SENSITIVE_FREE_TEXT',
    source: 'USER_INPUT',
    purpose: 'Reports submitted against inappropriate client reviews.',
    legal_basis_status: 'LEGAL_APPROVAL_REQUIRED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'RETAIN_IF_LEGALLY_REQUIRED',
    external_processors: ['Supabase Inc.'],
    notes: 'Contains free-text abuse allegations.',
  },

  // ---------------------------------------------------------------------------
  // REVIEWS & COMMUNITY FEEDBACK
  // ---------------------------------------------------------------------------
  {
    id: 'PROFESSIONAL_REVIEWS',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.professional_reviews',
    subject_role: 'CLIENT',
    data_category: 'USER_REVIEWS',
    classification: 'USER_GENERATED_CONTENT',
    sensitivity_level: 'POTENTIALLY_SENSITIVE_FREE_TEXT',
    source: 'USER_INPUT',
    purpose: 'Client ratings and reviews on professional service experiences.',
    legal_basis_status: 'SOURCE_CONFIRMED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'ANONYMIZE',
    external_processors: ['Supabase Inc.'],
    notes: 'Comments are free-text written by clients that may reference intimate activity or encounter details.',
  },
  {
    id: 'PROFESSIONAL_REVIEW_RESPONSES',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.professional_review_responses',
    subject_role: 'ADVERTISER',
    data_category: 'USER_REVIEWS',
    classification: 'USER_GENERATED_CONTENT',
    sensitivity_level: 'POTENTIALLY_SENSITIVE_FREE_TEXT',
    source: 'USER_INPUT',
    purpose: 'Professional responses to client reviews.',
    legal_basis_status: 'SOURCE_CONFIRMED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'DELETE',
    external_processors: ['Supabase Inc.'],
    notes: 'Responses authored by advertiser.',
  },
  {
    id: 'PROFESSIONAL_REVIEW_MODERATION_EVENTS',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.professional_review_moderation_events',
    subject_role: 'ADMIN',
    data_category: 'MODERATION_AUDIT',
    classification: 'AUDIT_RECORD',
    sensitivity_level: 'POTENTIALLY_SENSITIVE_FREE_TEXT',
    source: 'ADMINISTRATIVE_ACTION',
    purpose: 'Audit log of moderation decisions on reviews and responses.',
    legal_basis_status: 'LEGAL_APPROVAL_REQUIRED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'RETAIN_IF_LEGALLY_REQUIRED',
    external_processors: ['Supabase Inc.'],
    notes: 'Contains content_snapshot of review comments.',
  },

  // ---------------------------------------------------------------------------
  // CLIENTS & VIP MEMBERSHIPS
  // ---------------------------------------------------------------------------
  {
    id: 'CLIENT_MEMBERSHIPS',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.client_memberships',
    subject_role: 'CLIENT',
    data_category: 'MEMBERSHIP_ENTITLEMENT',
    classification: 'PRIVATE_PERSONAL',
    sensitivity_level: 'NOT_SENSITIVE',
    source: 'SYSTEM_DERIVED',
    purpose: 'Client account membership tier (FREE / VIP) and access expiration.',
    legal_basis_status: 'SOURCE_CONFIRMED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'DELETE',
    external_processors: ['Supabase Inc.'],
    notes: 'Account tier reference only.',
  },

  // ---------------------------------------------------------------------------
  // BILLING, SUBSCRIPTIONS & MONETIZATION
  // ---------------------------------------------------------------------------
  {
    id: 'SUBSCRIPTIONS',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.subscriptions',
    subject_role: 'ADVERTISER',
    data_category: 'SUBSCRIPTION_CONTRACT',
    classification: 'FINANCIAL_REFERENCE',
    sensitivity_level: 'NOT_SENSITIVE',
    source: 'USER_INPUT',
    purpose: 'Records professional subscription contracts, renewal dates, and status.',
    legal_basis_status: 'LEGAL_APPROVAL_REQUIRED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'RETAIN_IF_LEGALLY_REQUIRED',
    external_processors: ['Supabase Inc.'],
    notes: 'Commercial subscription records. Financial reference only; no credit card numbers stored.',
  },
  {
    id: 'BILLING_WEBHOOK_EVENTS',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.billing_webhook_events',
    subject_role: 'SYSTEM',
    data_category: 'PAYMENT_WEBHOOK_AUDIT',
    classification: 'AUDIT_RECORD',
    sensitivity_level: 'NOT_SENSITIVE',
    source: 'EXTERNAL_PROVIDER',
    purpose: 'Idempotency and audit ledger for incoming payment webhook transactions.',
    legal_basis_status: 'LEGAL_APPROVAL_REQUIRED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'RETAIN_IF_LEGALLY_REQUIRED',
    external_processors: ['Supabase Inc.'],
    notes: 'Stores transaction IDs and timestamps. No PAN/card data stored.',
  },
  {
    id: 'BILLING_OVERRIDES',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.billing_overrides',
    subject_role: 'ADVERTISER',
    data_category: 'COMMERCIAL_OVERRIDE',
    classification: 'AUDIT_RECORD',
    sensitivity_level: 'NOT_SENSITIVE',
    source: 'ADMINISTRATIVE_ACTION',
    purpose: 'Administrative overrides for trial/founder entitlements.',
    legal_basis_status: 'SOURCE_CONFIRMED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'RETAIN_IF_LEGALLY_REQUIRED',
    external_processors: ['Supabase Inc.'],
    notes: 'Audit log of commercial grants.',
  },
  {
    id: 'ENTITLEMENT_OVERRIDES',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.entitlement_overrides',
    subject_role: 'ADVERTISER',
    data_category: 'COMMERCIAL_OVERRIDE',
    classification: 'AUDIT_RECORD',
    sensitivity_level: 'NOT_SENSITIVE',
    source: 'ADMINISTRATIVE_ACTION',
    purpose: 'Specific entitlement bypasses granted to accounts.',
    legal_basis_status: 'SOURCE_CONFIRMED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'DELETE',
    external_processors: ['Supabase Inc.'],
    notes: 'Operational bypass configuration.',
  },
  {
    id: 'BILLING_ADMIN_AUDIT_LOGS',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.billing_admin_audit_logs',
    subject_role: 'ADMIN',
    data_category: 'ADMIN_AUDIT',
    classification: 'AUDIT_RECORD',
    sensitivity_level: 'NOT_SENSITIVE',
    source: 'ADMINISTRATIVE_ACTION',
    purpose: 'Comprehensive audit trail of admin actions altering billing, founders, or audience settings.',
    legal_basis_status: 'LEGAL_APPROVAL_REQUIRED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'RETAIN_IF_LEGALLY_REQUIRED',
    external_processors: ['Supabase Inc.'],
    notes: 'Contains actor and target account IDs.',
  },
  {
    id: 'PROFILE_BOOSTS',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.profile_boosts',
    subject_role: 'ADVERTISER',
    data_category: 'PROMOTIONAL_CAMPAIGNS',
    classification: 'FINANCIAL_REFERENCE',
    sensitivity_level: 'NOT_SENSITIVE',
    source: 'USER_INPUT',
    purpose: 'Records sponsored profile boost placements and time windows.',
    legal_basis_status: 'SOURCE_CONFIRMED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'DELETE',
    external_processors: ['Supabase Inc.'],
    notes: 'Promotional placement schedule.',
  },

  // ---------------------------------------------------------------------------
  // TELEMETRY & ANALYTICS
  // ---------------------------------------------------------------------------
  {
    id: 'ANALYTICS_EVENTS',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.analytics_events',
    subject_role: 'VISITOR',
    data_category: 'USAGE_TELEMETRY',
    classification: 'BEHAVIORAL_ANALYTICS',
    sensitivity_level: 'NOT_SENSITIVE',
    source: 'OBSERVED_TELEMETRY',
    purpose: 'Interaction telemetry (impressions, contact clicks, search execution) for marketplace performance.',
    legal_basis_status: 'SOURCE_CONFIRMED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'ANONYMIZE',
    external_processors: ['Supabase Inc.'],
    notes: 'Zero raw IPs stored or logged. Uses pseudonymous visitor_session_id stored in client localStorage.',
  },
  {
    id: 'PROFILE_DAILY_METRICS',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.profile_daily_metrics',
    subject_role: 'ADVERTISER',
    data_category: 'AGGREGATED_PERFORMANCE',
    classification: 'ANONYMIZED_OR_AGGREGATED',
    sensitivity_level: 'NOT_SENSITIVE',
    source: 'SYSTEM_DERIVED',
    purpose: 'Daily aggregated performance metrics per profile (impressions, views, contact clicks).',
    legal_basis_status: 'SOURCE_CONFIRMED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'DELETE',
    external_processors: ['Supabase Inc.'],
    notes: 'Aggregated numbers without individual visitor identifiers.',
  },
  {
    id: 'PLATFORM_DAILY_METRICS',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.platform_daily_metrics',
    subject_role: 'SYSTEM',
    data_category: 'AGGREGATED_PERFORMANCE',
    classification: 'ANONYMIZED_OR_AGGREGATED',
    sensitivity_level: 'NOT_SENSITIVE',
    source: 'SYSTEM_DERIVED',
    purpose: 'Platform-wide aggregated health and activity counters.',
    legal_basis_status: 'SOURCE_CONFIRMED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'NOT_APPLICABLE',
    external_processors: ['Supabase Inc.'],
    notes: 'Fully aggregated, no personal data.',
  },

  // ---------------------------------------------------------------------------
  // AGENDA & AVAILABILITY
  // ---------------------------------------------------------------------------
  {
    id: 'PROFESSIONAL_AVAILABILITY_SETTINGS',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.professional_availability_settings',
    subject_role: 'ADVERTISER',
    data_category: 'SCHEDULING_PREFERENCES',
    classification: 'PRIVATE_PERSONAL',
    sensitivity_level: 'NOT_SENSITIVE',
    source: 'USER_INPUT',
    purpose: 'Timezone, booking lead times, buffer minutes, and agenda operational parameters.',
    legal_basis_status: 'SOURCE_CONFIRMED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'DELETE',
    external_processors: ['Supabase Inc.'],
    notes: 'Operational scheduling parameters.',
  },
  {
    id: 'PROFESSIONAL_WEEKLY_AVAILABILITY',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.professional_weekly_availability',
    subject_role: 'ADVERTISER',
    data_category: 'WORKING_HOURS',
    classification: 'PUBLIC_PERSONAL',
    sensitivity_level: 'NOT_SENSITIVE',
    source: 'USER_INPUT',
    purpose: 'Recurring weekly availability windows by day of week and location.',
    legal_basis_status: 'SOURCE_CONFIRMED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'DELETE',
    external_processors: ['Supabase Inc.'],
    notes: 'Day and hour slots.',
  },
  {
    id: 'PROFESSIONAL_AVAILABILITY_EXCEPTIONS',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.professional_availability_exceptions',
    subject_role: 'ADVERTISER',
    data_category: 'SCHEDULE_EXCEPTIONS',
    classification: 'PRIVATE_PERSONAL',
    sensitivity_level: 'NOT_SENSITIVE',
    source: 'USER_INPUT',
    purpose: 'Date-specific schedule overrides, blocked vacation intervals, or custom hours.',
    legal_basis_status: 'SOURCE_CONFIRMED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'DELETE',
    external_processors: ['Supabase Inc.'],
    notes: 'Calendar dates and blocked hours.',
  },

  // ---------------------------------------------------------------------------
  // AI CONCIERGE (CURRENTLY STAGED / GATED)
  // ---------------------------------------------------------------------------
  {
    id: 'PROFESSIONAL_CONCIERGE_SETTINGS',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.professional_concierge_settings',
    subject_role: 'ADVERTISER',
    data_category: 'AI_AGENT_SETTINGS',
    classification: 'PRIVATE_PERSONAL',
    sensitivity_level: 'NOT_SENSITIVE',
    source: 'USER_INPUT',
    purpose: 'Configuration of virtual assistant tone, welcome text, qualification flags.',
    legal_basis_status: 'SOURCE_CONFIRMED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'DELETE',
    external_processors: ['Supabase Inc.'],
    notes: 'Settings and configuration parameters.',
  },
  {
    id: 'PROFESSIONAL_CONCIERGE_FAQS',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.professional_concierge_faqs',
    subject_role: 'ADVERTISER',
    data_category: 'AI_KNOWLEDGE_BASE',
    classification: 'PUBLIC_PERSONAL',
    sensitivity_level: 'POTENTIALLY_SENSITIVE_FREE_TEXT',
    source: 'USER_INPUT',
    purpose: 'Custom Q&A pairs used as ground truth for concierge replies.',
    legal_basis_status: 'SOURCE_CONFIRMED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'DELETE',
    external_processors: ['Supabase Inc.'],
    notes: 'Free-text questions and answers which may describe services, boundaries, or intimate practices.',
  },
  {
    id: 'CONCIERGE_CONVERSATIONS',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.concierge_conversations',
    subject_role: 'VISITOR',
    data_category: 'CONVERSATION_SESSIONS',
    classification: 'PRIVATE_PERSONAL',
    sensitivity_level: 'POTENTIALLY_SENSITIVE_FREE_TEXT',
    source: 'USER_INPUT',
    purpose: 'Tracks inquiry chat sessions between visitors and virtual assistant.',
    legal_basis_status: 'LEGAL_APPROVAL_REQUIRED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'DELETE',
    external_processors: ['OpenAI, L.L.C. (planned)', 'Supabase Inc.'],
    notes: 'Gated by CONCIERGE_WEB_PUBLIC_ENABLED=false. Uses visitor_session_id. Retention policy pending.',
  },
  {
    id: 'CONCIERGE_MESSAGES',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.concierge_messages',
    subject_role: 'VISITOR',
    data_category: 'CHAT_MESSAGES',
    classification: 'PRIVATE_PERSONAL',
    sensitivity_level: 'POTENTIALLY_SENSITIVE_FREE_TEXT',
    source: 'USER_INPUT',
    purpose: 'Message content exchanged in virtual concierge chat sessions.',
    legal_basis_status: 'LEGAL_APPROVAL_REQUIRED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'DELETE',
    external_processors: ['OpenAI, L.L.C. (planned)', 'Supabase Inc.'],
    notes: 'Free-text user messages that may inquire about intimate services, sexual preferences, or personal details.',
  },

  // ---------------------------------------------------------------------------
  // SECURITY & RATE LIMITING
  // ---------------------------------------------------------------------------
  {
    id: 'DISTRIBUTED_RATE_LIMITS',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.distributed_rate_limits',
    subject_role: 'SYSTEM',
    data_category: 'RATE_LIMIT_WINDOWS',
    classification: 'OPERATIONAL_SECURITY',
    sensitivity_level: 'NOT_SENSITIVE',
    source: 'SYSTEM_DERIVED',
    purpose: 'Distributed sliding-window rate limit counters to protect APIs against abuse.',
    legal_basis_status: 'SOURCE_CONFIRMED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'DELETE',
    external_processors: ['Supabase Inc.'],
    notes: 'Uses HMAC-derived pseudonymized keys. Raw client IP is never stored.',
  },

  // ---------------------------------------------------------------------------
  // DATA SUBJECT REQUESTS (LGPD-01)
  // ---------------------------------------------------------------------------
  {
    id: 'DATA_SUBJECT_REQUESTS',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.data_subject_requests',
    subject_role: 'ADVERTISER',
    data_category: 'PRIVACY_RIGHTS_REQUESTS',
    classification: 'AUDIT_RECORD',
    sensitivity_level: 'NOT_SENSITIVE',
    source: 'USER_INPUT',
    purpose: 'Canonical ledger tracking user privacy requests under LGPD.',
    legal_basis_status: 'SOURCE_CONFIRMED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'RETAIN_IF_LEGALLY_REQUIRED',
    external_processors: ['Supabase Inc.'],
    notes: 'Stores request type, status, safe details, resolution codes. Bound to requester_account_user_id with RESTRICT.',
  },
  {
    id: 'DATA_SUBJECT_REQUEST_EVENTS',
    system: 'SUPABASE_POSTGRES',
    storage_object: 'public.data_subject_request_events',
    subject_role: 'ADMIN',
    data_category: 'PRIVACY_RIGHTS_AUDIT',
    classification: 'AUDIT_RECORD',
    sensitivity_level: 'NOT_SENSITIVE',
    source: 'SYSTEM_DERIVED',
    purpose: 'Append-only audit ledger recording lifecycle transitions of DSR requests.',
    legal_basis_status: 'SOURCE_CONFIRMED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'RETAIN_IF_LEGALLY_REQUIRED',
    external_processors: ['Supabase Inc.'],
    notes: 'Strictly append-only via DB trigger prevent_dsr_events_mutation.',
  },

  // ---------------------------------------------------------------------------
  // CLIENT STORAGE & COOKIES
  // ---------------------------------------------------------------------------
  {
    id: 'COOKIE_AGE_VERIFICATION',
    system: 'CLIENT_STORAGE',
    storage_object: 'Cookie: velvet_adult_access',
    subject_role: 'VISITOR',
    data_category: 'COMPLIANCE_FLAGS',
    classification: 'OPERATIONAL_SECURITY',
    sensitivity_level: 'NOT_SENSITIVE',
    source: 'USER_INPUT',
    purpose: 'Stores confirmation that user is 18+ to satisfy adult content warning requirements.',
    legal_basis_status: 'SOURCE_CONFIRMED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'DELETE',
    external_processors: [],
    notes: '180-day lifespan. SameSite=Lax, Secure in HTTPS.',
  },
  {
    id: 'COOKIE_CONSENT_PREFERENCES',
    system: 'CLIENT_STORAGE',
    storage_object: 'Cookie: velvet_cookie_consent',
    subject_role: 'VISITOR',
    data_category: 'CONSENT_RECORD',
    classification: 'OPERATIONAL_SECURITY',
    sensitivity_level: 'NOT_SENSITIVE',
    source: 'USER_INPUT',
    purpose: 'Stores cookie consent choices (necessary vs analytics, version, timestamp).',
    legal_basis_status: 'SOURCE_CONFIRMED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'DELETE',
    external_processors: [],
    notes: 'Current version r6-v1. Marketing is strictly false.',
  },
  {
    id: 'LOCALSTORAGE_VISITOR_SESSION',
    system: 'CLIENT_STORAGE',
    storage_object: 'localStorage: ad_mkt_vsid',
    subject_role: 'VISITOR',
    data_category: 'SESSION_PSEUDONYM',
    classification: 'BEHAVIORAL_ANALYTICS',
    sensitivity_level: 'NOT_SENSITIVE',
    source: 'SYSTEM_DERIVED',
    purpose: 'Random UUID session identifier for correlating analytics events across pages within a visit.',
    legal_basis_status: 'SOURCE_CONFIRMED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'DELETE',
    external_processors: [],
    notes: 'Only populated when analytics consent is granted.',
  },
  {
    id: 'LOCALSTORAGE_IMPRESSION_SEEN',
    system: 'CLIENT_STORAGE',
    storage_object: 'localStorage: ad_mkt_imp_seen',
    subject_role: 'VISITOR',
    data_category: 'DEDUPLICATION_CACHE',
    classification: 'OPERATIONAL_SECURITY',
    sensitivity_level: 'NOT_SENSITIVE',
    source: 'SYSTEM_DERIVED',
    purpose: 'Temporary set of profile IDs seen in current session to prevent inflating impression counters.',
    legal_basis_status: 'SOURCE_CONFIRMED',
    retention_status: 'UNDEFINED',
    deletion_strategy: 'DELETE',
    external_processors: [],
    notes: 'Client-side deduplication only.',
  },
] as const
