import type { Metadata } from 'next'
import Link from 'next/link'
import { getRequestLocale } from '@/lib/i18n/server'
import { localizePathname } from '@/lib/i18n/routing'
export const metadata: Metadata = { title: 'Como funciona | Velvet', description: 'Entenda descoberta, verificação, publicação e contato na Velvet.' }
export default async function HowItWorksPage() {
  const locale = await getRequestLocale(); const en = locale === 'en'; const href = (p: string) => localizePathname(p, locale)
  const steps = en ? [['1. Discover','Search by city, area and available filters.'],['2. Understand the profile','Review public information, approved media and the verification notice.'],['3. Contact directly','Use a contact channel enabled by the professional. Velvet does not join the conversation.'],['4. For professionals','Create an account, complete identity and age verification, build the profile and submit content for moderation before publication.']] : [['1. Descubra','Busque por cidade, região e filtros disponíveis.'],['2. Entenda o perfil','Consulte informações públicas, mídia aprovada e o aviso de verificação.'],['3. Entre em contato diretamente','Use um canal habilitado pela profissional. A Velvet não participa da conversa.'],['4. Para profissionais','Crie uma conta, conclua a verificação de identidade e maioridade, monte o perfil e envie o conteúdo para moderação antes da publicação.']]
  return <article className="velvet-institutional-page"><header><p className="velvet-overline">{en ? 'HOW IT WORKS' : 'COMO FUNCIONA'}</p><h1>{en ? 'A clear path from discovery to direct contact.' : 'Um caminho claro da descoberta ao contato direto.'}</h1><p>{en ? 'Velvet provides the platform and safety controls; adults retain autonomy over their choices and conversations.' : 'A Velvet oferece a plataforma e controles de segurança; adultos mantêm autonomia sobre suas escolhas e conversas.'}</p></header>{steps.map(([title, body]) => <section key={title}><h2>{title}</h2><p>{body}</p></section>)}<nav className="velvet-institutional-actions"><Link href={href('/seguranca')}>{en ? 'Safety' : 'Segurança'}</Link><Link href={href('/anuncie')}>{en ? 'Advertise your profile' : 'Anuncie seu perfil'}</Link></nav></article>
}
