import type { Metadata } from 'next'
import { getRequestLocale } from '@/lib/i18n/server'
export const metadata: Metadata = { title: 'Cookies | Velvet', description: 'Saiba como a Velvet usa cookies e armazenamento local.' }
export default async function CookiesPage() {
  const en = (await getRequestLocale()) === 'en'
  return <article className="velvet-institutional-page"><header><p className="velvet-overline">{en ? 'COOKIE POLICY' : 'POLÍTICA DE COOKIES'}</p><h1>{en ? 'Storage with purpose and choice.' : 'Armazenamento com propósito e escolha.'}</h1><p>{en ? 'This policy explains the cookies and browser storage used by Velvet. You can reopen Cookie preferences in the footer at any time.' : 'Esta política explica os cookies e o armazenamento do navegador usados pela Velvet. Você pode reabrir Preferências de cookies no rodapé a qualquer momento.'}</p></header>
    <section><h2>{en ? 'Necessary' : 'Necessários'}</h2><p>{en ? 'Used for authentication, security, language, the 18+ acknowledgement and saving your privacy choices. They are required for the requested service and cannot be disabled in the preference panel.' : 'Usados para autenticação, segurança, idioma, confirmação 18+ e registro de suas escolhas de privacidade. São necessários para o serviço solicitado e não podem ser desativados no painel.'}</p></section>
    <section><h2>Analytics</h2><p>{en ? 'With your permission, first-party analytics measures searches, impressions, profile views and contact clicks. A random identifier is limited to the browser tab in sessionStorage. Do Not Track is respected. Withdrawing consent stops future collection and clears these session identifiers.' : 'Com sua permissão, analytics próprios medem buscas, impressões, visualizações de perfil e cliques de contato. Um identificador aleatório fica limitado à aba em sessionStorage. O sinal Não Rastrear é respeitado. Revogar o consentimento interrompe a coleta futura e remove esses identificadores de sessão.'}</p></section>
    <section><h2>Marketing</h2><p>{en ? 'Velvet currently has no advertising pixels or marketing trackers installed. This category is displayed for transparency and future control, and remains inactive.' : 'A Velvet não possui atualmente pixels de publicidade nem rastreadores de marketing instalados. A categoria é exibida para transparência e controle futuro e permanece inativa.'}</p></section>
    <section><h2>{en ? 'Duration and control' : 'Duração e controle'}</h2><p>{en ? 'Age and consent choices are retained for up to 180 days, unless you update them earlier or clear browser data. Authentication duration follows account security settings.' : 'As escolhas de idade e consentimento são mantidas por até 180 dias, salvo atualização anterior ou limpeza dos dados do navegador. A duração da autenticação segue as configurações de segurança da conta.'}</p></section>
  </article>
}

