import type { Metadata } from 'next'
import Link from 'next/link'
import { LegalDocument, type LegalSection } from '@/components/public/legal-document'
import { getPrivacyContactEmail } from '@/lib/legal'
import { buildCanonicalUrl } from '@/modules/seo/canonical'

export const metadata: Metadata = {
  title: { absolute: 'Termos de Uso | Velvet' },
  description: 'Regras para acesso e uso da plataforma Velvet.',
  alternates: { canonical: buildCanonicalUrl('/termos') },
}

export default function TermsPage() {
  const email = getPrivacyContactEmail()
  const contact = email ? <a href={`mailto:${email}`}>{email}</a> : <>o canal oficial que será publicado nesta página antes da entrada em produção</>
  const sections: LegalSection[] = [
    { id: 'aceitacao', title: 'Aceitação dos Termos', content: <p>Ao criar uma conta ou usar a Velvet, você declara ter lido e aceitado estes Termos e o Aviso de Privacidade. Se não concordar, não use a plataforma.</p> },
    { id: 'velvet', title: 'O que é a Velvet', content: <p>A Velvet é uma plataforma independente de descoberta e publicação de perfis profissionais. Ela oferece ferramentas de cadastro, verificação, moderação, busca, apresentação e contato direto.</p> },
    { id: 'maiores', title: 'Serviço exclusivamente para maiores de 18 anos', content: <p>A Velvet é destinada somente a adultos com 18 anos ou mais. Ao acessar ou criar uma conta, você declara cumprir esse requisito. É proibido cadastrar, representar, promover ou exibir qualquer pessoa menor de idade.</p> },
    { id: 'conta', title: 'Conta da profissional', content: <p>A profissional deve fornecer dados corretos, proteger suas credenciais e manter acesso ao e-mail cadastrado. A conta é pessoal e não pode ser cedida, vendida ou usada para representar outra pessoa.</p> },
    { id: 'verificacao', title: 'Verificação de identidade e maioridade', content: <p>A publicação depende de verificação por fornecedor especializado. A aprovação confirma apenas o resultado e o escopo do procedimento realizado; não constitui garantia ampla sobre declarações, conduta, disponibilidade ou qualidade profissional. Tentativas de burlar a verificação são proibidas.</p> },
    { id: 'perfil', title: 'Criação e manutenção do perfil', content: <p>A profissional é responsável por manter nome artístico, descrição, características, regiões, fotos e contatos corretos e atualizados. Os controles de visibilidade disponíveis devem ser usados com atenção, pois informações publicadas ficam acessíveis a visitantes.</p> },
    { id: 'conteudo', title: 'Conteúdo enviado pela profissional', content: <p>A profissional declara possuir direitos e autorizações sobre o conteúdo enviado e que sua publicação não viola lei, consentimento, privacidade, imagem, honra, propriedade intelectual ou direitos de terceiros.</p> },
    { id: 'licenca', title: 'Licença necessária para exibição do conteúdo', content: <p>A profissional mantém a titularidade de seu conteúdo e concede à Velvet, enquanto ele for necessário à operação da conta e do serviço, licença limitada, não exclusiva e revogável conforme estes Termos para armazenar, processar, ajustar tamanho ou formato, moderar, exibir e distribuir o conteúdo nas páginas da Velvet. Essa licença não transfere a propriedade das fotografias à Velvet.</p> },
    { id: 'regras', title: 'Regras de conteúdo', content: <p>É proibido conteúdo envolvendo ou sugerindo menores, falsidade de identidade, fraude, coerção, exploração, material sem consentimento, atividade ilegal, exposição de dados privados, violação de direitos de terceiros, código malicioso ou tentativa de contornar a segurança da plataforma. A lista não limita outras medidas necessárias diante de risco ou ilegalidade.</p> },
    { id: 'moderacao', title: 'Moderação', content: <p>Perfis, textos e mídias podem ser analisados, aprovados, restringidos, rejeitados, removidos ou isolados para revisão. A moderação reduz riscos, mas não representa endosso nem garantia integral sobre conteúdo fornecido por usuários.</p> },
    { id: 'publicacao', title: 'Publicação e despublicação', content: <p>A publicação depende cumulativamente de conta ativa, identidade e maioridade verificadas, perfil e mídia aprovados, área de atendimento válida e direito de publicação ativo. Alterações relevantes podem exigir nova moderação. Falta de pagamento, expiração, suspensão ou perda de algum requisito pode pausar ou despublicar o perfil sem apagá-lo automaticamente.</p> },
    { id: 'contato-direto', title: 'Contato entre visitantes e profissionais', content: <p>O contato ocorre diretamente pelos canais escolhidos pela profissional, fora de chat interno da Velvet. Cada pessoa decide se deseja iniciar ou continuar uma conversa e deve agir com respeito, segurança e dentro da lei.</p> },
    { id: 'papel', title: 'Papel da Velvet', content: <p>A Velvet oferece descoberta, perfil e contato. Não participa de conversas, negociações ou arranjos feitos fora da plataforma; não recebe pagamentos entre visitante e profissional; não atua como representante, empregadora, agência, garantidora ou parte desses entendimentos.</p> },
    { id: 'proibicoes', title: 'Condutas proibidas', content: <p>Não é permitido fraudar dados ou métricas, assediar pessoas, fazer engenharia reversa indevida, coletar perfis em massa, acessar conta alheia, testar vulnerabilidades sem autorização, distribuir malware, interferir no funcionamento, contornar controles ou usar a Velvet para finalidade ilegal.</p> },
    { id: 'seguranca', title: 'Segurança', content: <p>Você deve usar senha forte, manter dispositivos protegidos e comunicar suspeitas pelos canais oficiais quando disponíveis. Não compartilhe documentos de identidade por canais informais. Medidas de segurança reduzem riscos, mas não eliminam todas as ameaças.</p> },
    { id: 'disponibilidade', title: 'Disponibilidade da plataforma', content: <p>A Velvet pode passar por manutenção, atualização, falhas de fornecedores ou interrupções. Buscamos continuidade razoável, sem prometer disponibilidade ininterrupta ou preservação eterna de qualquer recurso.</p> },
    { id: 'suspensao', title: 'Suspensão e encerramento de contas', content: <p>Podemos restringir, suspender ou encerrar acesso quando houver violação destes Termos, risco à segurança, obrigação legal ou perda dos requisitos de publicação, observados os direitos aplicáveis. A aplicação ainda não oferece encerramento integral por autosserviço; solicitações podem ser encaminhadas por contato oficial.</p> },
    { id: 'planos', title: 'Planos e direitos de publicação', content: <p>A arquitetura admite planos, preços, períodos, cancelamento ao fim do ciclo e direitos de publicação. No estado atual, o provedor real de pagamentos ainda não está integrado. Condições comerciais, cobrança, reembolso e cancelamento deverão ser apresentadas antes de uma contratação paga e submetidas a revisão jurídica.</p> },
    { id: 'propriedade', title: 'Propriedade intelectual', content: <p>A marca, identidade visual, software, textos institucionais e demais materiais próprios da Velvet são protegidos. Estes Termos não concedem licença além do uso normal da plataforma. Conteúdo da profissional permanece sujeito à licença operacional limitada descrita acima.</p> },
    { id: 'privacidade', title: 'Privacidade', content: <p>O tratamento de dados pessoais é explicado no <Link href="/privacidade">Aviso de Privacidade</Link>. Ao tornar informações públicas, a profissional reconhece que elas poderão ser acessadas por visitantes.</p> },
    { id: 'alteracoes', title: 'Alterações dos Termos', content: <p>Podemos atualizar estes Termos para refletir mudanças no produto, riscos e legislação. A versão vigente será publicada aqui e, quando necessário, solicitaremos nova aceitação.</p> },
    { id: 'responsabilidades', title: 'Responsabilidades e limitações', content: <p>A Velvet não garante a exatidão de toda declaração do usuário, a disponibilidade ou qualidade profissional, a conduta das partes nem a legalidade de arranjos externos. Cada pessoa responde por suas escolhas, conteúdo e conduta. Nada nestes Termos exclui responsabilidade ou direito que não possa ser afastado pela legislação aplicável.</p> },
    { id: 'legislacao', title: 'Legislação aplicável', content: <p>Estes Termos são interpretados conforme a legislação brasileira, inclusive regras de proteção de dados e normas de proteção do consumidor quando aplicáveis. A definição de foro e demais cláusulas processuais depende de revisão jurídica.</p> },
    { id: 'contato', title: 'Contato', content: <p>Solicitações relacionadas a privacidade podem ser encaminhadas para {contact}. Outros canais institucionais deverão ser definidos antes da produção; nenhum endereço, empresa, CNPJ ou representante é presumido neste documento.</p> },
  ]
  return <LegalDocument eyebrow="Termos · versão operacional inicial" title="Termos de Uso da Velvet" introduction={<p>Estas regras organizam o uso responsável da plataforma por visitantes e profissionais. Elas não substituem orientação jurídica e serão submetidas a revisão especializada antes da versão definitiva.</p>} sections={sections} />
}
