import type { Metadata } from 'next'
import { LegalDocument, type LegalSection } from '@/components/public/legal-document'
import { getPrivacyContactEmail } from '@/lib/legal'
import { buildCanonicalUrl } from '@/modules/seo/canonical'
import { getRequestLocale } from '@/lib/i18n/server'

export const metadata: Metadata = {
  title: { absolute: 'Privacidade | Velvet' },
  description: 'Entenda como a Velvet trata dados pessoais e como exercer seus direitos.',
  alternates: { canonical: buildCanonicalUrl('/privacidade') },
}

export default async function PrivacyPage() {
  const locale = await getRequestLocale()
  if (locale === 'en') return <LegalDocument eyebrow="PRIVACY · INITIAL OPERATIONAL VERSION" title="Privacy at Velvet" introduction={<p>This notice explains how Velvet handles personal data, the choices available to adults and the current operational limits. Final controller and privacy-contact details require business and legal confirmation.</p>} sections={[
    { id: 'scope', title: 'Scope and data categories', content: <p>Velvet may process account, profile, contact, service-area, approved media, verification status, moderation, security and usage data needed to operate the platform. Public profiles exclude legal identity and internal verification details.</p> },
    { id: 'purposes', title: 'Purposes and legal grounds', content: <p>Data is used to create and secure accounts, verify identity and age, moderate and publish profiles, provide search and direct contact, prevent abuse, measure the service and meet legal obligations. Depending on context, grounds may include contract, legal obligation, legitimate interests, rights protection and consent.</p> },
    { id: 'providers', title: 'Providers and sharing', content: <p>Supabase supports authentication, database and storage; a specialized provider may perform identity and age verification; hosting suppliers deliver the application. Data may also be disclosed where lawfully required. No payment provider is currently integrated.</p> },
    { id: 'analytics', title: 'Analytics and cookies', content: <p>Optional first-party analytics runs only after consent and measures searches, impressions, profile views and contact clicks. A random identifier is limited to sessionStorage, Do Not Track is respected and no marketing trackers are installed.</p> },
    { id: 'retention', title: 'Retention and security', content: <p>Data is retained only while needed for stated purposes, security, legal duties and rights. Access controls, private media delivery and moderation reduce risk, but no system can promise absolute security.</p> },
    { id: 'rights', title: 'LGPD rights', content: <p>Subject to applicable conditions, individuals may request confirmation, access, correction, information, portability, anonymization, blocking or deletion, object to certain processing, withdraw consent and request review of relevant automated decisions.</p> },
    { id: 'contact', title: 'Privacy contact and legal inputs', content: <p>The official privacy contact, controller identity, company registration, address and DPO information have not been provided and must be published before final legal release. No identity or address is assumed here.</p> },
    { id: 'minors', title: 'Children and adolescents', content: <p>Velvet is exclusively for adults aged 18 or over. Registration, publication or participation by minors is prohibited and suspected content may be blocked and escalated.</p> },
  ]} />
  const privacyEmail = getPrivacyContactEmail()
  const contact = privacyEmail
    ? <p>Envie sua solicitação para <a href={`mailto:${privacyEmail}`}>{privacyEmail}</a>. Poderemos pedir informações razoáveis para confirmar sua identidade e proteger seus dados.</p>
    : <p>O canal oficial de privacidade será disponibilizado nesta página antes da entrada da Velvet em produção.</p>

  const sections: LegalSection[] = [
    { id: 'sobre', title: 'Sobre este Aviso de Privacidade', content: <><p>Este aviso descreve como a Velvet trata dados pessoais ao oferecer uma plataforma independente de descoberta e publicação de perfis profissionais. Ele se aplica a visitantes e profissionais e deve ser lido com os Termos de Uso.</p><p>A Velvet é destinada exclusivamente a pessoas com 18 anos ou mais. Este texto é uma versão operacional inicial e poderá ser atualizado após revisão jurídica.</p></> },
    { id: 'dados-tratados', title: 'Quais dados podemos tratar', content: <p>Tratamos somente dados relacionados às finalidades descritas neste aviso: dados de conta, perfil, contato, localização de atendimento, mídia, verificação, uso, segurança, moderação e, quando aplicável, assinatura e direitos de publicação.</p> },
    { id: 'dados-profissional', title: 'Dados fornecidos pela profissional', content: <p>Durante cadastro e onboarding, a profissional pode fornecer e-mail, senha, nome artístico, texto de apresentação, idade pública opcional, características físicas escolhidas, idiomas, canais de contato, regiões de atendimento e fotografias. As escolhas são validadas e podem passar por moderação.</p> },
    { id: 'conta-autenticacao', title: 'Dados de conta e autenticação', content: <p>O acesso é administrado por autenticação do Supabase. São tratados e-mail, credenciais de acesso de forma protegida pelo provedor, identificadores de conta, status, progresso do onboarding e registros de aceite das versões de Termos e Privacidade. Cookies de sessão podem ser usados para manter e renovar a autenticação.</p> },
    { id: 'perfil-publico', title: 'Informações do perfil público', content: <p>Quando o perfil atende aos critérios de publicação, podem ser exibidos nome artístico, descrição, idade pública, características físicas conforme opções de visibilidade existentes, idiomas, áreas de atendimento, fotografias aprovadas e canais de contato habilitados. Identidade legal, dados internos de verificação e identificadores técnicos não compõem o perfil público.</p> },
    { id: 'fotos', title: 'Fotos e mídia', content: <p>As fotografias incluem o arquivo, tipo, tamanho, dimensões, posição, indicação de foto principal e estados de processamento e moderação. Os arquivos ficam em armazenamento não público e somente mídia aprovada é entregue por links temporários. Fotos rejeitadas, em análise, em quarentena ou marcadas como excluídas não são publicadas.</p> },
    { id: 'localizacao', title: 'Localização e regiões de atendimento', content: <p>A profissional escolhe áreas de atendimento cadastradas na plataforma e indica uma região principal. A Velvet não solicita endereço residencial ou localização precisa nesse fluxo; as áreas escolhidas podem aparecer publicamente no perfil e na busca.</p> },
    { id: 'contato', title: 'Dados de contato', content: <p>A profissional pode informar WhatsApp, telefone direto ou usuário do Telegram e habilitar individualmente os canais disponíveis. O contato acontece diretamente entre visitante e profissional, fora da infraestrutura de mensagens da Velvet. Cliques em canais de contato podem gerar métricas de uso, mas a Velvet não participa do conteúdo da conversa.</p> },
    { id: 'verificacao', title: 'Verificação de identidade e maioridade', content: <><p>A publicação exige verificação de identidade e confirmação de maioridade por um fornecedor especializado. Esse fornecedor pode processar documento, imagem facial, prova de vida e outros dados necessários ao procedimento, inclusive dados biométricos quando aplicável ao fluxo contratado.</p><p>A Velvet recebe e mantém identificadores de sessão, estado do processo, confirmações de identidade e idade, país verificado, datas relevantes e registros técnicos de eventos. A aplicação atual não armazena cópias brutas de documentos, selfies, biometrias, CPF completo ou data de nascimento completa em suas tabelas de verificação.</p></> },
    { id: 'dados-tecnicos', title: 'Dados técnicos e de uso', content: <p>Podemos tratar informações técnicas necessárias a autenticação, segurança, prevenção de abuso, funcionamento e diagnóstico, como identificadores de sessão, data e hora, páginas ou recursos usados, dados de requisição e registros de erro. Endereços IP podem ser usados temporariamente para limitar abuso; nos fluxos de analytics e denúncias auditados, o IP bruto não é persistido.</p> },
    { id: 'analytics', title: 'Analytics', content: <p>A Velvet mantém analytics próprios sobre buscas, impressões, visualizações e cliques em contato, além de contexto como cidade, região, página, posição, filtros, origem e atribuição de destaque. Um identificador aleatório por aba é guardado em <em>sessionStorage</em>, sem cookie de analytics e sem rastreamento entre sessões; o sinal “Não Rastrear” do navegador é respeitado. Profissionais recebem apenas métricas agregadas, sem identificadores de visitantes.</p> },
    { id: 'finalidades', title: 'Por que tratamos esses dados', content: <p>Usamos dados para criar e proteger contas; verificar identidade e maioridade; montar, moderar e publicar perfis; entregar mídia aprovada; operar busca e contato direto; administrar assinatura e direito de publicação; medir o desempenho do serviço; prevenir fraude e abuso; cumprir obrigações e responder a solicitações. Aplicamos finalidade, adequação e necessidade para limitar cada uso ao que é pertinente.</p> },
    { id: 'bases-legais', title: 'Bases legais aplicáveis', content: <p>Conforme o contexto, o tratamento poderá se apoiar na execução de contrato e de procedimentos solicitados pela titular, cumprimento de obrigações legais ou regulatórias, exercício regular de direitos, proteção da vida ou da integridade física, legítimo interesse avaliado com salvaguardas e consentimento quando ele for exigido. A definição final das bases para verificação biométrica, moderação e demais operações sensíveis está sujeita a revisão jurídica.</p> },
    { id: 'compartilhamento', title: 'Compartilhamento e operadores', content: <p>Dados podem ser tratados por fornecedores necessários à operação: Supabase para autenticação, banco de dados e armazenamento; Didit para verificação de identidade e maioridade quando configurado; e o provedor de hospedagem da aplicação. Um provedor de pagamentos ainda não está integrado. Também poderemos compartilhar dados quando exigido por lei, autoridade competente ou para defender direitos, sempre dentro dos limites aplicáveis.</p> },
    { id: 'dados-publicos', title: 'Dados tornados públicos pela profissional', content: <p>Informações selecionadas para exibição pública podem ser acessadas, copiadas ou compartilhadas por visitantes e mecanismos externos. A profissional controla os canais de contato e algumas opções de visibilidade previstas no produto; não há controle individual de visibilidade para todo campo. Recomendamos não incluir no perfil informações que não devam se tornar públicas.</p> },
    { id: 'armazenamento', title: 'Armazenamento e segurança', content: <p>Adotamos controles técnicos e organizacionais compatíveis com o serviço, incluindo autenticação, separação de acesso por conta, operações privilegiadas no servidor, armazenamento privado de mídia, entrega temporária de fotos aprovadas, moderação e validação de eventos externos. Nenhum sistema é absolutamente seguro; medidas são revistas de acordo com riscos e evolução do produto.</p> },
    { id: 'transferencias', title: 'Transferências internacionais', content: <p>Fornecedores de infraestrutura e verificação podem tratar ou armazenar dados fora do Brasil, conforme suas regiões e suboperadores. Antes da produção, a Velvet deve confirmar locais de processamento, contratos e mecanismos aplicáveis às transferências internacionais.</p> },
    { id: 'retencao', title: 'Retenção', content: <p>Guardamos dados pelo tempo necessário às finalidades informadas, à segurança, à prevenção de fraude, ao exercício de direitos e às obrigações aplicáveis. A aplicação mantém históricos de aceite, verificação, moderação, eventos, assinatura e auditoria quando necessários. Os prazos específicos e rotinas de descarte ainda serão formalizados e revisados juridicamente.</p> },
    { id: 'direitos', title: 'Direitos do titular', content: <p>Nos termos da LGPD e conforme aplicável, você pode pedir confirmação e acesso; correção; informação sobre compartilhamentos; anonimização, bloqueio ou exclusão de dados desnecessários, excessivos ou tratados em desconformidade; portabilidade quando regulamentada; eliminação de dados tratados com consentimento, ressalvadas hipóteses legais; informação sobre a possibilidade de negar consentimento; revogação do consentimento; oposição; e revisão ou informação sobre decisões exclusivamente automatizadas que afetem seus interesses.</p> },
    { id: 'solicitacoes', title: 'Como solicitar seus direitos', content: <>{contact}<p>As solicitações serão analisadas conforme sua natureza e a legislação. A exclusão não é instantânea e certos registros podem ser preservados quando a manutenção for exigida ou permitida por lei ou necessária à segurança e ao exercício de direitos. A aplicação ainda não oferece exclusão integral da conta por autosserviço.</p></> },
    { id: 'menores', title: 'Crianças e adolescentes', content: <p>A Velvet é exclusivamente 18+. Não permitimos cadastro, publicação ou participação de crianças e adolescentes. Conteúdo ou indício envolvendo menores pode ser bloqueado, removido e encaminhado para as medidas cabíveis.</p> },
    { id: 'alteracoes', title: 'Alterações deste aviso', content: <p>Este aviso poderá mudar para acompanhar o produto, fornecedores, exigências legais e orientações de autoridades. A versão aplicável será publicada nesta página e, quando necessário, solicitaremos nova ciência ou consentimento.</p> },
    { id: 'contato-final', title: 'Contato', content: contact },
  ]

  return <LegalDocument eyebrow="Privacidade · versão operacional inicial" title="Privacidade na Velvet" introduction={<p>Clareza sobre seus dados faz parte da experiência Velvet. Aqui explicamos o que é tratado, por quê, com quem e quais escolhas e direitos você possui.</p>} sections={sections} />
}
