'use client'
import Image from 'next/image'
import { useState, useTransition } from 'react'
import { useI18n } from '@/components/i18n'
import { confirmVideoUploadAction, deleteVideoAction, reorderVideosAction, requestVideoUploadAction } from '@/modules/videos/actions'
import { MAX_VIDEO_DURATION_SECONDS, MAX_VIDEO_FILE_SIZE_BYTES, MAX_VIDEOS_PER_PROFILE, VIDEO_MIME_TYPES } from '@/modules/videos/schemas'
import type { ManageableProfileVideo, ProfileVideo } from '@/modules/videos/types'

async function metadata(file:File){return new Promise<{duration:number;poster:Blob}>((resolve,reject)=>{const url=URL.createObjectURL(file),video=document.createElement('video');video.preload='metadata';video.muted=true;video.onloadedmetadata=()=>{if(!Number.isFinite(video.duration)||video.duration<=0||video.duration>MAX_VIDEO_DURATION_SECONDS){URL.revokeObjectURL(url);reject(new Error('duration'));return}video.currentTime=Math.min(.1,video.duration/2)};video.onseeked=()=>{const canvas=document.createElement('canvas');canvas.width=Math.min(video.videoWidth,1280);canvas.height=Math.round(canvas.width*video.videoHeight/video.videoWidth);canvas.getContext('2d')?.drawImage(video,0,0,canvas.width,canvas.height);canvas.toBlob(blob=>{URL.revokeObjectURL(url);blob?resolve({duration:video.duration,poster:blob}):reject(new Error('poster'))},'image/jpeg',.8)};video.onerror=()=>reject(new Error('format'));video.src=url})}
export function VideoManager({initialVideos}:{initialVideos:ManageableProfileVideo[]}){const {locale}=useI18n(),en=locale==='en';const [videos,setVideos]=useState(initialVideos),[message,setMessage]=useState(''),[pending,start]=useTransition();const active=videos.filter(v=>!v.deleted_at&&v.status!=='DELETED');
 const choose=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(!VIDEO_MIME_TYPES.includes(file.type as never)||file.size<1||file.size>MAX_VIDEO_FILE_SIZE_BYTES){setMessage(en?'Use MP4/WebM up to 50 MB.':'Use MP4/WebM com até 50 MB.');return}if(active.length>=3)return;setMessage(en?'Reading video…':'Lendo vídeo…');try{await metadata(file);const req=await requestVideoUploadAction({mime_type:file.type,file_size_bytes:file.size});if(!req.success)throw new Error(req.error);setMessage(en?'Uploading…':'Enviando…');const meta=await metadata(file);const [v,p]=await Promise.all([fetch(req.data.videoUploadUrl,{method:'PUT',headers:{'Content-Type':file.type},body:file}),fetch(req.data.posterUploadUrl,{method:'PUT',headers:{'Content-Type':'image/jpeg'},body:meta.poster})]);if(!v.ok||!p.ok)throw new Error('upload');const result=await confirmVideoUploadAction({video_id:req.data.videoId});if(!result.success)throw new Error(result.error);setVideos(x=>[...x,{...result.data,posterUrl:URL.createObjectURL(meta.poster)}]);setMessage(en?'Video sent for moderation.':'Vídeo enviado para moderação.')}catch(err){setMessage(err instanceof Error&&err.message==='duration'?(en?'Maximum duration is 30 seconds.':'A duração máxima é 30 segundos.'):(err instanceof Error?err.message:(en?'Upload failed.':'Falha no upload.')))}};
 const replace=(next:ProfileVideo[])=>setVideos(next.map(v=>({...v,posterUrl:videos.find(x=>x.id===v.id)?.posterUrl??null})));const move=(i:number,d:-1|1)=>{const n=[...active],[a,b]=[i,i+d];[n[a],n[b]]=[n[b],n[a]];start(async()=>{const r=await reorderVideosAction({video_ids:n.map(v=>v.id)});if(r.success)replace(r.data)})};const remove=(id:string)=>{if(!confirm(en?'Delete this video?':'Excluir este vídeo?'))return;start(async()=>{const r=await deleteVideoAction({video_id:id});if(r.success)replace(r.data);else setMessage(r.error)})};
 return <section className="video-manager" aria-labelledby="video-manager-title"><header><div><p className="dashboard-eyebrow">{en?'VIDEOS':'VÍDEOS'}</p><h2 id="video-manager-title">{en?'Profile videos':'Vídeos do perfil'}</h2></div><span>{active.length}/{MAX_VIDEOS_PER_PROFILE}</span></header><p>{en?'Up to 3 videos · 30 seconds · 50 MB each · MP4/WebM. Videos are private until approved.':'Até 3 vídeos · 30 segundos · 50 MB cada · MP4/WebM. Vídeos ficam privados até aprovação.'}</p><input id="video-upload" hidden type="file" accept={VIDEO_MIME_TYPES.join(',')} onChange={choose} disabled={pending||active.length>=3}/><label className="photo-add" htmlFor="video-upload" aria-disabled={active.length>=3}>{en?'Add video':'Adicionar vídeo'}</label>{message&&<p role="status">{message}</p>}<ol className="video-manager-grid">{active.map((v,i)=><li key={v.id}>{v.posterUrl?<Image src={v.posterUrl} width={320} height={240} alt={en?`Video ${i+1} poster`:`Capa do vídeo ${i+1}`}/>:<div className="video-poster-placeholder"/>}<span className={`photo-status photo-status--${v.status.toLowerCase()}`}>{v.status.replaceAll('_',' ')}</span><small>{v.duration_seconds?`${v.duration_seconds}s · `:''}{(v.file_size_bytes/1048576).toFixed(1)} MB</small><div><button disabled={pending||i===0} onClick={()=>move(i,-1)}>←</button><button disabled={pending||i===active.length-1} onClick={()=>move(i,1)}>→</button><button disabled={pending} onClick={()=>remove(v.id)}>{en?'Delete':'Excluir'}</button></div></li>)}</ol></section>}

