'use server'
import { createAdminClient } from '@/lib/supabase/admin'
import { getProfileByAccountUserId } from '@/modules/profiles/dal'
import { requireVerifiedAdvertiser } from '@/modules/verification/dal'
import { inspectPoster, inspectVideo } from './inspection'
import { MAX_POSTER_FILE_SIZE_BYTES, MAX_VIDEOS_PER_PROFILE, ReorderVideosSchema, RequestVideoUploadSchema, VideoIdSchema } from './schemas'
import { getProfileVideos, getVideoById } from './dal'
import type { ProfileVideo, VideoActionResult, VideoUploadUrls } from './types'

async function owner(){const {account}=await requireVerifiedAdvertiser();const profile=await getProfileByAccountUserId(account.id);if(!profile)throw new Error('Perfil não encontrado.');return profile}
async function removeObjects(paths:string[]){const {error}=await createAdminClient().storage.from('profile-videos').remove(paths);if(error)console.error('[videos:cleanup]',error.message)}
export async function requestVideoUploadAction(input:unknown):Promise<VideoActionResult<VideoUploadUrls>>{try{const parsed=RequestVideoUploadSchema.safeParse(input);if(!parsed.success)return {success:false,error:'Use MP4/WebM com até 50 MB.'};const profile=await owner(),admin=createAdminClient(),videos=await getProfileVideos(profile.id);if(videos.length>=MAX_VIDEOS_PER_PROFILE)return {success:false,error:'Limite de 3 vídeos atingido.'};const id=crypto.randomUUID(),ext=parsed.data.mime_type==='video/mp4'?'mp4':'webm',storage=`profiles/${profile.id}/${id}.${ext}`,poster=`profiles/${profile.id}/${id}-poster.jpg`;const {error}=await admin.from('profile_videos').insert({id,profile_id:profile.id,storage_path:storage,poster_storage_path:poster,file_size_bytes:parsed.data.file_size_bytes,mime_type:parsed.data.mime_type,position:videos.length+1});if(error)return {success:false,error:'Não foi possível preparar o upload.'};const [v,p]=await Promise.all([admin.storage.from('profile-videos').createSignedUploadUrl(storage),admin.storage.from('profile-videos').createSignedUploadUrl(poster)]);if(v.error||p.error||!v.data||!p.data){await admin.from('profile_videos').delete().eq('id',id);return {success:false,error:'Não foi possível preparar o armazenamento seguro.'}}return {success:true,data:{videoId:id,videoUploadUrl:v.data.signedUrl,posterUploadUrl:p.data.signedUrl,expiresAt:new Date(Date.now()+7200000).toISOString()}}}catch{return {success:false,error:'Não foi possível preparar o vídeo.'}}}
export async function confirmVideoUploadAction(input:unknown):Promise<VideoActionResult<ProfileVideo>>{try{const parsed=VideoIdSchema.safeParse(input);if(!parsed.success)return {success:false,error:'Vídeo inválido.'};const profile=await owner(),video=await getVideoById(parsed.data.video_id);if(!video||video.profile_id!==profile.id||video.deleted_at)return {success:false,error:'Vídeo não encontrado.'};if(video.status==='PENDING_MODERATION')return {success:true,data:video};if(video.status!=='UPLOADING')return {success:false,error:'Upload não pode ser confirmado.'};const admin=createAdminClient();const [vf,pf]=await Promise.all([admin.storage.from('profile-videos').download(video.storage_path),admin.storage.from('profile-videos').download(video.poster_storage_path)]);if(vf.error||pf.error||!vf.data||!pf.data)return {success:false,error:'Vídeo ou capa ainda não recebido.'};const vb=new Uint8Array(await vf.data.arrayBuffer()),pb=new Uint8Array(await pf.data.arrayBuffer());if(pb.length>MAX_POSTER_FILE_SIZE_BYTES)throw new Error('poster too large');const inspected=inspectVideo(vb);inspectPoster(pb);if(inspected.mimeType!==video.mime_type||vb.length!==video.file_size_bytes)throw new Error('metadata mismatch');const {data,error}=await admin.from('profile_videos').update({status:'PENDING_MODERATION',duration_seconds:inspected.durationSeconds}).eq('id',video.id).select('*').single();if(error||!data)throw new Error('update failed');return {success:true,data:data as ProfileVideo}}catch(e){return {success:false,error:e instanceof Error&&e.message.includes('duration')?'O vídeo deve ter no máximo 30 segundos.':'O arquivo não corresponde a um MP4/WebM válido.'}}}
export async function reorderVideosAction(input:unknown):Promise<VideoActionResult<ProfileVideo[]>>{try{const parsed=ReorderVideosSchema.safeParse(input);if(!parsed.success)return {success:false,error:'Ordem inválida.'};const profile=await owner(),current=await getProfileVideos(profile.id);if(new Set(parsed.data.video_ids).size!==current.length||parsed.data.video_ids.some(id=>!current.some(v=>v.id===id)))return {success:false,error:'Inclua todos os vídeos exatamente uma vez.'};const admin=createAdminClient(),{error}=await admin.rpc('reorder_profile_videos',{p_profile_id:profile.id,p_video_ids:parsed.data.video_ids});if(error)return {success:false,error:'Não foi possível reordenar.'};return {success:true,data:await getProfileVideos(profile.id)}}catch{return {success:false,error:'Não foi possível reordenar.'}}}
export async function deleteVideoAction(input:unknown):Promise<VideoActionResult<ProfileVideo[]>>{try{const parsed=VideoIdSchema.safeParse(input);if(!parsed.success)return {success:false,error:'Vídeo inválido.'};const profile=await owner(),video=await getVideoById(parsed.data.video_id);if(!video||video.profile_id!==profile.id||video.deleted_at)return {success:false,error:'Vídeo não encontrado.'};const admin=createAdminClient();const {error}=await admin.from('profile_videos').update({status:'DELETED',deleted_at:new Date().toISOString()}).eq('id',video.id);if(error)return {success:false,error:'Não foi possível excluir.'};await removeObjects([video.storage_path,video.poster_storage_path]);return {success:true,data:await getProfileVideos(profile.id)}}catch{return {success:false,error:'Não foi possível excluir.'}}}
export async function getVideoPlaybackUrlAction(input:unknown):Promise<VideoActionResult<string>>{const parsed=VideoIdSchema.safeParse(input);if(!parsed.success)return {success:false,error:'Vídeo inválido.'};const video=await getVideoById(parsed.data.video_id);if(!video||video.status!=='APPROVED'||video.deleted_at)return {success:false,error:'Vídeo indisponível.'};const admin=createAdminClient();const {data:eligible}=await admin.from('v_publication_eligible_profiles').select('profile_id').eq('profile_id',video.profile_id).maybeSingle();if(!eligible)return {success:false,error:'Vídeo indisponível.'};const {data,error}=await admin.storage.from('profile-videos').createSignedUrl(video.storage_path,900);return error||!data?{success:false,error:'Vídeo indisponível.'}:{success:true,data:data.signedUrl}}
