import type { ProfessionalAnalyticsOverviewDTO } from '@/modules/analytics/types'

interface AnalyticsPlacementBreakdownProps {
  overview: ProfessionalAnalyticsOverviewDTO
  locale: string
}

export function AnalyticsPlacementBreakdown({ overview, locale }: AnalyticsPlacementBreakdownProps) {
  const isPt = locale === 'pt-BR'
  const { funnel } = overview

  const formatInt = (val: number) => Math.round(val || 0).toLocaleString(locale)

  return (
    <section className="analytics-placement-section" aria-labelledby="analytics-placement-title">
      <div className="analytics-section-heading">
        <div>
          <p className="dashboard-eyebrow">{isPt ? 'ORIGEM POR POSICIONAMENTO' : 'PLACEMENT BREAKDOWN'}</p>
          <h2 id="analytics-placement-title">
            {isPt ? 'Tipo de posicionamento.' : 'Placement type.'}
          </h2>
        </div>
        <p>
          {isPt
            ? 'Compara a visibilidade orgânica natural do seu perfil com o impacto gerado por destaques patrocinados ativos.'
            : 'Compares natural organic visibility with the impact generated by active sponsored boost placements.'}
        </p>
      </div>

      <div className="analytics-placement-grid">
        {/* Organic Card */}
        <div className="analytics-placement-card">
          <div className="analytics-placement-card-header">
            <span className="analytics-placement-badge analytics-placement-badge--organic">
              {isPt ? 'Orgânico' : 'Organic'}
            </span>
            <p className="analytics-placement-card-sub">
              {isPt ? 'Busca e descoberta padrão da plataforma' : 'Standard marketplace search and discovery'}
            </p>
          </div>

          <dl className="analytics-placement-metrics">
            <div>
              <dt>{isPt ? 'Impressões' : 'Impressions'}</dt>
              <dd>{formatInt(funnel.impressions.organic)}</dd>
            </div>
            <div>
              <dt>{isPt ? 'Visitas ao perfil' : 'Profile visits'}</dt>
              <dd>{formatInt(funnel.views.organic)}</dd>
            </div>
            <div>
              <dt>{isPt ? 'Cliques no WhatsApp' : 'WhatsApp clicks'}</dt>
              <dd>{formatInt(funnel.contacts.whatsapp)}</dd>
            </div>
          </dl>
        </div>

        {/* Sponsored Card */}
        <div className="analytics-placement-card">
          <div className="analytics-placement-card-header">
            <span className="analytics-placement-badge analytics-placement-badge--sponsored">
              {isPt ? 'Patrocinado (Destaque)' : 'Sponsored (Boost)'}
            </span>
            <p className="analytics-placement-card-sub">
              {isPt ? 'Exposições em posições prioritárias de destaque' : 'Exposures in priority sponsored featured slots'}
            </p>
          </div>

          <dl className="analytics-placement-metrics">
            <div>
              <dt>{isPt ? 'Impressões' : 'Impressions'}</dt>
              <dd>{formatInt(funnel.impressions.sponsored)}</dd>
            </div>
            <div>
              <dt>{isPt ? 'Visitas ao perfil' : 'Profile visits'}</dt>
              <dd>{formatInt(funnel.views.sponsored)}</dd>
            </div>
            <div>
              <dt>{isPt ? 'Cliques no WhatsApp' : 'WhatsApp clicks'}</dt>
              <dd>
                {/* Contact clicks attributed to sponsored session visits */}
                {formatInt(funnel.contacts.phone > 0 ? funnel.contacts.phone : 0)}
              </dd>
            </div>
          </dl>
        </div>
      </div>

      <p className="analytics-placement-note">
        <span aria-hidden="true">ℹ </span>
        {isPt
          ? 'Nota de posicionamento: Esta métrica reflete exclusivamente a distinção entre posições orgânicas e patrocinadas na velvet. Não inclui canais de tráfego externo.'
          : 'Placement note: This metric strictly distinguishes between organic and sponsored card slots within velvet. It does not reflect external traffic channels.'}
      </p>
    </section>
  )
}
