import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'
import { buildSearchPageHref } from '@/modules/search/presentation'

const read = (path: string) => readFileSync(resolve(process.cwd(), path), 'utf8')

describe('Velvet R5 Search / Explore contracts', () => {
  const city = read('app/[city]/page.tsx')
  const location = read('app/[city]/[neighborhood]/page.tsx')
  const filters = read('components/search/public-search-filters.tsx')
  const card = read('components/public/public-profile-card.tsx')
  const css = read('app/velvet-public.css')
  const r5Css = css.slice(css.indexOf('VELVET R5'))
  const messages = read('lib/i18n/messages/public.ts')

  it('1. scopes the redesign to R5 Explore surfaces', () => expect(city).toContain('velvet-explore--r5'))
  it('2. applies the same R5 shell to neighborhoods', () => expect(location).toContain('velvet-explore--r5'))
  it('3. keeps the canonical search DAL', () => expect(city).toContain('executeSearch'))
  it('4. does not mutate database state', () => expect(city + location).not.toMatch(/\.insert\(|\.update\(|\.delete\(|\.upsert\(/))
  it('5. retains server-side search analytics', () => expect(city + location).toContain('recordSearchPerformedEvent'))
  it('6. retains crawler analytics suppression', () => expect(city + location).toContain('isSearchCrawler'))
  it('7. exposes no invented verified query filter', () => expect(filters).not.toMatch(/params\.set\(['"]verified/))
  it('8. preserves all existing query params when applying filters', () => expect(filters).toContain('searchParams.toString()'))
  it('9. removes page when filters change', () => expect(filters).toContain("params.delete('page')"))
  it('10. keeps neighborhood in the route contract', () => expect(filters).toContain('city.slug}/${location}'))
  it('11. preserves locale-aware filter navigation', () => expect(filters).toContain('localizePathname(path, locale)'))
  it('12. preserves active filters in pagination', () => expect(city + location).toContain('buildSearchPageHref'))
  it('13. omits page=1 from presentation URLs', () => expect(buildSearchPageHref('/sao-paulo', { cabelo: 'BLONDE', page: '2' }, 1, 'pt-BR')).toBe('/sao-paulo?cabelo=BLONDE'))
  it('14. builds locale-aware English pagination', () => expect(buildSearchPageHref('/sao-paulo', { idade_min: '25' }, 2, 'en')).toBe('/en/sao-paulo?idade_min=25&page=2'))
  it('15. preserves repeated query values', () => expect(buildSearchPageHref('/sao-paulo', { cabelo: ['BLACK', 'BLONDE'] }, 3, 'pt-BR')).toBe('/sao-paulo?cabelo=BLACK&cabelo=BLONDE&page=3'))
  it('16. uses one truthful filter trigger', () => expect(filters.match(/className={`velvet-filter-trigger/g)).toHaveLength(1))
  it('17. displays removable active filter chips', () => expect(filters).toContain('velvet-active-filters'))
  it('18. localizes categorical options', () => expect(filters).toContain("t('search.option.hair.black')"))
  it('19. supports Escape dismissal', () => expect(filters).toContain("event.key === 'Escape'"))
  it('20. traps keyboard focus', () => expect(filters).toContain("event.key === 'Tab'"))
  it('21. restores trigger focus', () => expect(filters).toContain('triggerRef.current?.focus()'))
  it('22. locks body scroll while open', () => expect(filters).toContain("document.body.style.overflow = 'hidden'"))
  it('23. exposes modal semantics', () => expect(filters).toContain('aria-modal="true"'))
  it('24. exposes expanded state on the trigger', () => expect(filters).toContain('aria-expanded={isOpen}'))
  it('25. enforces 18+ age input bounds', () => expect(filters).toContain('min="18" max="99"'))
  it('26. uses a search-only card variant', () => expect(card).toContain("variant?: 'default' | 'search'"))
  it('27. leaves the default card variant intact for Home', () => expect(card).toContain("variant = 'default'"))
  it('28. localizes profile links from search cards', () => expect(card).toContain('localizePathname(`/perfil/${profile.slug}`, locale)'))
  it('29. keeps search photography at 4:5', () => expect(r5Css).toContain('aspect-ratio: 4 / 5'))
  it('30. keeps four-column desktop results', () => expect(css).toContain('grid-template-columns:repeat(4,minmax(0,1fr))'))
  it('31. keeps the existing tablet three-column contract', () => expect(css).toContain('grid-template-columns:repeat(3,minmax(0,1fr))'))
  it('32. keeps the existing mobile two-column contract', () => expect(css).toContain('grid-template-columns:repeat(2,minmax(0,1fr))'))
  it('33. gives filter controls shared minimum heights', () => expect(r5Css).toContain('min-height: var(--control-h)'))
  it('34. keeps mobile card metadata at a readable floor', () => expect(r5Css).toContain('font-size: 13px'))
  it('35. uses the shared empty-state primitive', () => expect(city + location).toContain('<VelvetEmptyState'))
  it('36. localizes empty state content in PT and EN', () => expect(messages.match(/'search.noResultsTitle':/g)).toHaveLength(2))
  it('37. preserves canonical metadata construction', () => expect(city + location).toMatch(/construct(City|Location)Metadata/))
  it('38. preserves canonical breadcrumb JSON-LD', () => expect(city + location).toContain('<JsonLd'))
  it('39. preserves responsive next/image sizing', () => expect(card).toContain('sizes="(max-width: 640px) 100vw'))
  it('40. contains no business system changes in R5 presentation files', () => expect(filters + card).not.toMatch(/Didit|billing|entitlement|service_role|supabase/i))
})
